Adds minimum-coverage option
se2p/pynguin pull request #45
Opened 2023-07-08 17:51 UTC by Kucki2018

Users can now decide from the command line (CLI) whether to stop the program after a minimum coverage has been reached and the coverage has remained the same over multiple iterations.

2 new arguments:
--minimum-coverage-quick=1.0
--minimum-iteration-quick=10

2023-07-08 18:04 UTC, Kucki2018 reviewed
Small Syntax Error >= instead of =>

2023-07-10 07:02 UTC, stephanlukasczyk requested changes
Thanks for this contribution!

I very much like the idea of having an option to stop the search if a certain coverage level has been reached.  However, I do have some suggestions one this. Basically, I am asking you to refactor this change into a `StoppingCondition`, which would remove the duplicate code and allow for easier future adoption.

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/configuration.py
> +    """Stops the algorithm if minimum coverage is reached and coverage doesn't change over minimum_iteration_quick (default=10) iterations"""
I believe this description is somewhat unclear.  While it should be clear from the description that `minimum_coverage_quick` and `minimum_iteration_quick` are related, I'd focus more on the actual coverage value in the description of this variable.

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/dynamosaalgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
Violates the naming style in Python: we prefer underscore notation over camel case, e.g., `coverage_cache` instead of `coverageCache`.

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/dynamosaalgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
I would prefer to not querying the configuration settings directly here but abstract this functionality (see next comment).

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/dynamosaalgorithm.py
> +                    coverageCounter = 1
I would prefer to not have this functionality (which is repeated in all algorithm implementations) directly added to the algorithms.  I would strongly suggest that it should be a `StoppingCondition`, similar to all other stopping conditions.

Such an approach has two advantages: it does not require code clones in all algorithms (which can easily be forgotton when creating a new algorithm or changing things) and it abstracts away the concrete functionality.  The algorithms does not need to know about the concrete condition, it only shall check whether a stopping condition is met and if so, stop its iterations.

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/mioalgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/mioalgorithm.py
> +                    coverageCounter = 1
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/mosaalgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/mosaalgorithm.py
> +                    coverageCounter = 1
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/randomalgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/randomalgorithm.py
> +                    coverageCounter = 1
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/randomsearchalgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/randomsearchalgorithm.py
> +                    coverageCounter = 1
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/randomsearchalgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/randomsearchalgorithm.py
> +                    coverageCounter = 1
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/wholesuitealgorithm.py
> +        minIter = config.configuration.stopping.minimum_iteration_quick
See my comment in the `dynamosaalgorithm.py`

2023-07-10 07:02 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/wholesuitealgorithm.py
> +                    coverageCounter = 1
See my comment in the `dynamosaalgorithm.py`

2023-07-15 21:26 UTC, Kucki2018 commented on src/pynguin/ga/algorithms/dynamosaalgorithm.py
> +                    coverageCounter = 1
Yes, that is possible! I'm working on that. I had this idea from the start but wasn't sure if I could get the current coverage within the stopping condition. I can see the current iteration and get the tsc.TestSuiteChromosome. I guess I need to pull current coverage from that tsc? I'll take a look and maybe post a question here if I can't find the get_coverage().

2023-07-16 06:17 UTC, stephanlukasczyk commented on src/pynguin/ga/algorithms/dynamosaalgorithm.py
> +                    coverageCounter = 1
You can just call [`get_coverage()`](https://github.com/se2p/pynguin/blob/33be9852d6cec0101f13b11a7b07cdaebf55359f/src/pynguin/ga/chromosome.py#L131) on the `Chromosome` that is given as the `individual` parameter.

2023-08-04 18:36 UTC, Kucki2018 commented
All done now. No more duplicate code.

2023-08-09 20:06 UTC, stephanlukasczyk requested changes
Thank you for refactoring this and addressing my previous remarks.  I've some further remarks, unfortunately, some of which are not only nitpicks but necessary to make the code actually work.

Please also provide unit tests for your newly introduced stopping condition.

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +    def _init_(self, min_coverage: float, min_iterations: int):
The name of a constructor has to be `__init__` with two underscores each.

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +        super()._init_()
The call has to be `super().__init__()` with *two* underscores each.

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +        self._last_coverage = 0.0 #Cache the coverage from last iteration
If I remember correctly, the [`black`](https://github.com/psf/black) code style forces you to use two spaces before the `#` character and one after it.  Please run the `black` formatter before pushing, cf. Pynguin's documentation.

Additionally, I'd prefer to have private attributes having a name with two leading underscores.

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +        assert min_iterations > 0.0
You might want to check these criteria *before* calling the constructor of this class.  Furthermore, there is not only a minium reasonable coverage value but also a maximum (`< 1.0`).

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +        self._min_coverage = min_coverage #Minimum coverage from the configuration
See my comment on lines 176 to 178.

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +    def _str_(self):
The method's name has to be `__str__` with two underscores each.

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +        return f"Reached minimum coverage: {self.current_value()}/{self.limit()}"
You could also directly access the respective attributes instead of yet another method call to `current_value()` and `limit()`.

2023-08-09 20:06 UTC, stephanlukasczyk commented on src/pynguin/ga/stoppingcondition.py
> +        self._min_coverage = limit
You might want to add a check, whether the limit is actually reasonable, e.g., `assert 0.0 < limit < 1.0` or similar.

2023-08-11 12:06 UTC, Kucki2018 commented
I have processed/fixed all of your comments. I'm not sure how unit tests work here in Pynguin. I added a new file "tests/ga/stoppingconditions/test_minimumcoveragestoppingcondition.py".

I also tested the stop condition extensively myself.

2023-08-18 13:12 UTC, closed without merging