Refactor the architecture to add support for running the test cases in subprocesses
se2p/pynguin pull request #82
Opened 2024-12-09 18:23 UTC by BergLucas

Hi,

I'm making this pull request to coordinate the implementation of the test case execution in subprocesses. The goal is to highlight the prototype code I've already done and compare it to the current code. This will allow me to point out the problems I had to deal with and the solutions I found. I'm pretty sure there are still things that can be improved because I was fairly new to the codebase when I started this branch and there are surely things that can be optimized so don't hesitate to make comments.

## An architecture based on observers

The current architecture of Pynguin is based on observers for calculating various information. This makes Pynguin very flexible and configurable but it complicates execution in subprocesses. Indeed, it's rather complicated to call a main process observer from a subprocess because a link has to be made at some point, and data has to be transferred with each call.

That's why I chose a different approach in my prototype. I noticed that all observers interacted mostly with test cases and results. This is due to the fact that there was a constraint in their specification that limited their memory to the thread they were in for certain methods. By extending this constraint slightly to say that it applied to threads or subprocesses now, this almost made it possible to send them to another process, since all the data manipulated would remain included in their memories and in the results, which was going to be sent back to the main process anyway. The problem was that some observers also used other data in some methods. However, the use of this other data was limited to the `after_test_case_execution_outside_thread` functions. This is why I came up with the idea of splitting the observers into 2 parts, the part that will be executed on the main process (ExecutionObserver), where we'll call `after_test_case_execution_outside_thread`, and the part sent and executed on the subprocess (RemoteExecutionObserver) with the rest of the methods.

This has several advantages:

Firstly, this would allow Pynguin to continue working in the same way as before if we don't want to use subprocesses. In this case, we just need to run the RemoteExecutionObserver on the main process and everything will work in the same way.

Secondly, it limits the amount of information exchanged, as we only need to send the remote observers and don't need to send all the data used by the entire observer.

Finally, it retains Pynguin's flexibility while allowing observers to be executed in subprocesses.

(Note: I've renamed the observer methods to better match the new names)

### Current Architecture
![CurrentArchitecture](https://github.com/user-attachments/assets/902a4727-915a-4d85-8dd7-4c94a8bd212a)

### Prototype Architecture
![PrototypeArchitecture](https://github.com/user-attachments/assets/22cfea69-c089-4603-a175-68bd353b084d)

## A fairly complex data transfer

The current class architecture was not designed to be sent from one process to another. As a result, there are references between classes all over the place, and sending an object using pickle sometimes means sending all the data that Pynguin manipulates. Fortunately, when a new process is created, the memory is copied directly without going through pickle, which allows us to transfer data that pickle doesn't support and to be faster. However, the problem arises when transferring data from the subprocess to the main process. Indeed, this transfer has to be carried out using pickle and, with all the references, there's a big bottleneck which means that a lot of data has to be copied, and this sometimes causes crashes as some types just can't be serialized using pickle. This can be partly mitigated by using [dill](https://pypi.org/project/dill/), which is a pickle extension that supports more types, but it doesn't fix everything.

In my prototype, I managed to make everything necessary serializable using dill, but the best thing would be to redesign the data that needs to be sent so that this doesn't happen.

In addition, there's a special case concerning the tracer. For the moment, the tracer is installed when the target module is imported. However, during the memory copy to create the subprocess, the tracer is also copied, except that its reference becomes different from the one I'm passing as an argument to the function executed in the subprocess. Therefore, I have to modify it after the execution of the subprocess to be able to retrieve the information that the tracer obtained during the execution of the test case. It's annoying, but the other solution, which consisted in reinstrumenting the module after executing the submodule, created a big loss of performance, so it just wasn't acceptable.

## Some necessary improvements

At the moment, the creation of error-revealing test cases is very ugly, they're created on the fly and they're not minimized to make it easy to find the bug. I think it would be interesting to handle them better, but that would mean tweaking the algorithms, and I didn't have the time back then.

## Note

The `src/pynguin/instrumentation/tracer.py` file is mainly composed of classes that have been transferred from the `src/pynguin/testcase/execution.py` file because there were circular imports and this is why there are so many line changes. 

## Refactoring plan

I don't think it would be a good idea to merge this entire pull request at once, so I suggest that we do certain steps in other pull requests to better test and discuss each addition. In order, I suggest that we do the following:

1. Refactor the tracer to allow easy changes and avoid recursive imports later.
2. Add an execute_multiple function to execute a list of tests at once. For the moment, this won't change the behavior, but it's an important function for speeding up the subprocess execution.
3. Refactor the observers to have remote observers.
4. Optimization of the results that are sent back to the subprocess.
5. Add the subprocess executor (in this branch).

What do you think of this plan?

Don't hesitate to criticize or validate certain parts so that I can implement them ! 🙂

2024-12-11 12:53 UTC, stephanlukasczyk commented
Hi @BergLucas ,
This is an impressive and remarkable work! You mention that it is probably too big to be merged directly.  I am happy to discuss options and possibilities, because I think it would be nice to have this functionality in Pynguin.

One question: if I want to run this, I just have to add the `--subprocess` flag?

2024-12-11 17:07 UTC, stephanlukasczyk commented
Shall I do yet another run to collect some data on the behaviour, comparing the current execution, and the one from this PR?

2024-12-11 22:17 UTC, BergLucas commented
This PR just contains the code that had already been benchmarked against the classic execution that we discussed in issue #74, but where the few bugs I had found had been corrected. So, we could do another benchmark, but its usefulness would be limited for now. I think it would be more interesting to do a benchmark later to check that the refactoring hasn't caused any loss of performance on classic execution and to compare the performance of my prototype with the performance of the final code where data transfer has been optimized.

2024-12-12 06:54 UTC, stephanlukasczyk commented
That's fine for me as well, I'd have suggested to benchmark this anyway at some point, to be sure we do not introduce any issues in existing code.

Do you already have plans how you want to integrate this into `main`?  You know the changes best; I'd argue that rebasing it to `main`/merge `main` into this branch would be necessary to resolve the merge conflicts, however, we could also do some incremental approach.

2025-01-14 09:51 UTC, stephanlukasczyk commented
Sorry @BergLucas I totally missed to notification for this.

I'd prefer scheduling a call on this, I'll send you an email. Maybe it's easier to discuss directly.

2025-02-24 23:43 UTC, BergLucas commented
Even though the pull request is much smaller now, it would still be better to split it again by making another pull request containing only the refactoring of the observers and small changes to the executor. This would make the subprocesses code as readable as possible as it's not the most optimised code currently. I have quite a bit of time tomorrow to do this.

2025-02-25 07:39 UTC, stephanlukasczyk commented
> Even though the pull request is much smaller now, it would still be better to split it again by making another pull request containing only the refactoring of the observers and small changes to the executor. This would make the subprocesses code as readable as possible as it's not the most optimised code currently. I have quite a bit of time tomorrow to do this.

Whatever you prefer. As said, I am happy with both—having a selection of small PRs or one large.

2025-03-03 19:03 UTC, BergLucas commented
Hi @stephanlukasczyk @LuKrO2011 ,

Now that PR #89 and #90 are merged, the actual code that handles execution in subprocesses is much clearer. I've added a few comments and specifications to the parts where I've done unusual things to try and explain my approach.

In principle, all that's left is code to help `pickle` to serialize the classes we need, `state` methods to transfer data manually when we have no choice, and the new subprocess executor. At the meeting, you told me that it wasn't necessary to optimize performance in this PR, so in my opinion, the PR is almost ready to be merged. I just want to talk about the `_save_crash_tests` function which is used to save tests that have caused a subprocess to crash. I don't think it belongs in the executor, but I wasn't sure where to put it because I was afraid of modifying the behaviour of the test generation algorithms unintentionally. Don't hesitate to give me your opinion on where it could be moved.

Once this little change has been made, I think a benchmark of the 2 executors could be interesting to make sure that all the changes haven't broken anything and to see if there are any differences between the 2.

Thanks in advance for your feedback!

2025-03-03 22:31 UTC, stephanlukasczyk commented
> Hi @stephanlukasczyk @LuKrO2011 ,
> 
> Now that PR #89 and #90 are merged, the actual code that handles execution in subprocesses is much clearer. I've added a few comments and specifications to the parts where I've done unusual things to try and explain my approach.
> 
> In principle, all that's left is code to help `pickle` to serialize the classes we need, `state` methods to transfer data manually when we have no choice, and the new subprocess executor. At the meeting, you told me that it wasn't necessary to optimize performance in this PR so in my opinion, the PR is almost ready to be merged. I just want to talk about the `_save_crash_tests` function which is used to save tests that have caused a subprocess to crash. I don't think it belongs in the executor, but I wasn't sure where to put it because I was afraid of modifying the behaviour of the test generation algorithms unintentionally. Don't hesitate to give me your opinion on where it could be moved.
> 
> Once this little change has been made, I think a benchmark of the 2 executors could be interesting to make sure that all the changes haven't broken anything and to see if there are any differences between the 2.
> 
> Thanks in advance for your feedback!

Still, I really really appreciate the effort you made! I told you this before and it's been an amazing work you did.  I'll try to have a closer look tomorrow evening, please give me some time to look at this closely and think about it.

2025-03-04 09:31 UTC, LuKrO2011 requested changes
Thank you also from my side for your great work.
Regarding `_save_crash_tests`: We write the stats in the `stats` module, the test cases in the `generator` module and the configuration in the `configuration_writer`module. In other words, this is grouped by topic and we don't have a specific module for this. Thus I would say, `_save_crash_tests` can/should stay where it is at the moment, too. Maybe we can address this in a future PR/MR.
Regarding tests/benchmarking: I can take care of this, but IIRC @stephanlukasczyk has already something ready.

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/__init__.py
> +    return InstrLocation, (
We need this custom specification because InstrLocation uses `__slots__`, right? Maybe add this as comment?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/__init__.py
> +    return _UNSET, ()
`_UNSET` is a singleton so removing this would lead to multiple `_UNSET` objects being created instead of having just one? Maybe add this as comment?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/cli.py
> +    import multiprocess as mp
Firstly, I suggest moving this to main, or maybe even better define a method `_setup_multiprocess` and call it from main, similarly as done for `_setup_output_path`, `_setup_logging` etc. Or is there a reason for this being called before `sys.exit(...)`? 
Secondly, can we move this to a later point, e.g. after parsing the arguments? If so, should we guard this using `if config.configuration.subprocess:`?
Lastly, the documentation says that this is needed because for POSIX except macOS the default is `fork` and we want the same behaviour across all platforms. If that is right, please add a comment stating this as well.

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +        new_global_namespace.pop("__builtins__", None)
Add a comment why removing `__builtins__` is necessary

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +            "has_builtins": "__builtins__" in self._global_namespace,
Firstly: Isn't this always `True`? Secondly: I think this is a bit confusing. When this is `True` the actual `__builtins__` are not there, instead they got removed. Maybe rename it to something like `original_has_builtins`?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +            self.add_new_module_alias("builtins", "__builtins__")
So overall this means, that the `__builtins__` from the subprocess are used instead of unnecessarily transferring them from the main process over, which makes sense. As far as I know, Pynguin does not overwrite anything from `__builtins__` anywhere atm so this is fine. However, maybe add this restriction as comment?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +        new_global_namespace = self._global_namespace.copy()
Using a shallow copy does not have any negative side effects, because we move the stuff over to a subprocess anyway, right?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +                raise RuntimeError("Bug in Pynguin!")
We recently decided to just log the error and return an `ExecutionResult(timeout=True)` to allow Pynguin to recover. 
IIRC you told us that this seems to be related to `rich`, right? Did you make any other discoveries regarding this?
Besides that, is there a reason to handle this differently with subprocess execution?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +        ] = receiving_connection.recv()
IIRC you told us that creating the subprocess and sending data to it is quick, while receiving the results is slow. So the limiting part of this is receiving `ExecutionResult`? Can you please add a comment according to your observations why this is/might be the case?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +                raise RuntimeError("Bug in Pynguin!")
See comment for `execute`

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +    def execute_multiple(  # noqa: D102, C901
This method has quite some code duplicates with `execute`, but I am not able to come up with an idea on how to reduce those in a meaningful way either. Any ideas?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +        SubprocessTestCaseExecutor._replace_tracer(tracer)
This method has quite some code duplicates with its single-case variant. Can we remove the single-variant and pass a tuple with a single value to this multi-variant instead?

2025-03-04 09:31 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +    def _fix_result_for_pickle(result: ExecutionResult) -> None:  # noqa: C901
Reduce code duplicates. Maybe using a `Template Method Pattern`:
```
@staticmethod
def _fix_unpicklable(
    result: Any,
    attr_name: str,
    filter_func: Callable[[Any], Any],
    clear_func: Callable[[Any], None]
) -> None:
...
```

2025-03-04 12:23 UTC, BergLucas commented on src/pynguin/cli.py
> +    import multiprocess as mp
If I put that in the `main` function, I get these errors in the tests :

```
    mp.set_start_method("spawn")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocess.context.DefaultContext object at 0x7f6d7400af20>, method = 'spawn', force = False

    def set_start_method(self, method, force=False):
        if self._actual_context is not None and not force:
>           raise RuntimeError('context has already been set')
E           RuntimeError: context has already been set
```

2025-03-04 12:35 UTC, LuKrO2011 commented on src/pynguin/cli.py
> +    import multiprocess as mp
I assume you did not call it twice but removed it the first time. So I guess the context is set somehow automatically, causing this error. Did you try putting it at the start inside the main function? Maybe something else is setting the context before?
In this case, the right context (spawn) is already set, so one could skip it. However, it is then unclear what happens if the wrong context is set and we try to adjust it (will it succeed then or raise the same error).
Another idea might be to set `force` to `True`.
See also: https://github.com/pytorch/pytorch/issues/3492

We can also just leave it as it is and add a comment why it is at this place and not inside main, I guess.

2025-03-04 13:04 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +            self.add_new_module_alias("builtins", "__builtins__")
I didn't do it for that reason. It's just that during my tests, Pynguin was crashing because of this module so I made the best fix I could think of.

2025-03-04 13:06 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +        new_global_namespace = self._global_namespace.copy()
Yes, the goal here was just to be able to remove the `__builtins__` module from pickle serialization.

2025-03-04 13:15 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +                raise RuntimeError("Bug in Pynguin!")
I haven't had much time to look into this problem since then, but when I was doing my master's thesis, I noticed that there was a good chance that Pynguin's freeze problems came from a GIL deadlock. And, indeed, the problem behaved differently depending on whether or not the `rich` module was used.

Regarding the change from an exception to a log message, I forgot to change it there but there's no reason not to change it.

2025-03-04 13:15 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +                raise RuntimeError("Bug in Pynguin!")
I haven't had much time to look into this problem since then, but when I was doing my master's thesis, I noticed that there was a good chance that Pynguin's freeze problems came from a GIL deadlock. And, indeed, the problem behaved differently depending on whether or not the `rich` module was used.

Regarding the change from an exception to a log message, I forgot to change it there but there's no reason not to change it.

2025-03-04 13:26 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +        ] = receiving_connection.recv()
In my opinion, the problem comes from the fact that we use `VariableReference`s and `UniqueInstruction` in the `ExecutionResult` to find out which assertions have been executed. However, these classes are connected to the bytecode, CFGs, test cases, etc. and by transitivity, we send almost all the data defining the test cases. I didn't check everything manually but I did a bit of profiling and most of the time was spent serialising the data via pickle.

2025-03-04 13:37 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +    def _fix_result_for_pickle(result: ExecutionResult) -> None:  # noqa: C901
I also think that this function is terrible but I haven't found anything better. I had also considered the use of callable as you mentioned but I got the impression that it would make everything more complex without necessarily improving the duplication of code by much.

Current:
```python
        try:
            if exception_bad_items := dill.detect.baditems(result.exceptions):
                SubprocessTestCaseExecutor._log_different_results(
                    "Unpicklable exceptions",
                    exception_bad_items,
                )
                result.exceptions = {
                    position: exception
                    for position, exception in result.exceptions.items()
                    if exception not in exception_bad_items
                }
        except Exception as exception:  # noqa: BLE001
            SubprocessTestCaseExecutor._log_different_results(
                "Failed to fix exceptions for pickle",
                exception,
            )
            result.exceptions.clear()
```

Proposition:
```python
        def fix_bad_items(exception_bad_items: dict) -> None:
            result.exceptions = {
                position: exception
                for position, exception in result.exceptions.items()
                if exception not in exception_bad_items
            }
        
        def clear_bad_items(exception: Exception) -> None:
            result.exceptions.clear()

        self._fix_unpicklable(
            result.exceptions,
            "Unpicklable exceptions",
            "Failed to fix exceptions for pickle",
            fix_bad_items,
            clear_bad_items
        )
```

It's up to what you prefer then.

2025-03-04 13:39 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +        SubprocessTestCaseExecutor._replace_tracer(tracer)
We could indeed do that.

2025-03-04 13:50 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +        ] = receiving_connection.recv()
Thanks for clarification :)

2025-03-04 13:53 UTC, BergLucas commented on src/pynguin/cli.py
> +    import multiprocess as mp
It's because we use the `main` function in multiple tests so the `set_start_method` is called multiple times.

2025-03-04 14:05 UTC, LuKrO2011 commented on src/pynguin/cli.py
> +    import multiprocess as mp
Ahh, now I understand. I got it wrong previously. We had some similar issues with logging. A solution might be to call `importlib.reload("multiprocess")` for tests where we use the `main` function. But for now it's probably best to leave it where it is.

2025-03-04 14:06 UTC, LuKrO2011 commented on src/pynguin/testcase/execution.py
> +    def _fix_result_for_pickle(result: ExecutionResult) -> None:  # noqa: C901
Let's wait for @stephanlukasczyk's opinion on this.

2025-03-04 14:26 UTC, BergLucas commented on src/pynguin/testcase/execution.py
> +    def execute_multiple(  # noqa: D102, C901
I've implemented it using execute_multiple

2025-03-04 18:22 UTC, stephanlukasczyk commented on src/pynguin/testcase/execution.py
> +    def _fix_result_for_pickle(result: ExecutionResult) -> None:  # noqa: C901
Personally, I like the proposed new variant better. The current one, with the `try`-`except` and the nested `if` in my opinion is quite complex to reason about, whereas the two functions `fix_bad_items` and `clear_bad_items` are concise and simple.  So, I vote for the proposed variant.

2025-03-04 18:23 UTC, stephanlukasczyk commented
> Regarding tests/benchmarking: I can take care of this, but IIRC @stephanlukasczyk has already something ready.

I should have something ready, yes.  The experiments, I ran previously, just executed on the current version of this PR.  I'll set it up and start it tonight and come back to you with the results.

2025-04-02 08:37 UTC, LuKrO2011 commented
I just quickly evaluated the data (thanks @stephanlukasczyk for running an experiment).
Requiring at least 80% (= 8 runs * 2 configuration) = 16 successful runs, 323/359 modules remain:
![clipboard3](https://github.com/user-attachments/assets/72a66782-f761-4616-9f6a-7abc0607d722)

2025-04-04 05:28 UTC, LuKrO2011 commented
In the last check, a lot of runs crashed due to "ModuleNotFoundError" suggesting a bug in the dataset or the evaluation. Thus, I re-run the evaluation. This time, requiring at least 80% (= 8 runs * 2 configuration) = 16 successful runs, 648/669 modules remain:
![clipboard11](https://github.com/user-attachments/assets/920ea8a4-826e-4e0e-a202-189909319545)

2025-04-04 09:11 UTC, merged

2025-04-04 21:36 UTC, BergLucas commented
Hi @stephanlukasczyk and @LuKrO2011,

After a few months of work, this branch is finally merged so thanks again for your reviews and discussions that made this possible.

Now that it is merged, I guess it would be nice to do a small paper that discusses the advantages and disadvantages of using the subprocess executor compared to the classic executor. Given that we all contributed to this work, it would be nice to do a paper on this together. If you're interested, we could plan a meeting in the next weeks to organise this.